### PR TITLE
Support negative spins in ducc back-end

### LINKED ISSUE #66: Can't use negative spins with ducc
When trying to transform via ducc with negative spins, I get an error.

For example, I modify [this line of `ducc_demo.py`](https://github.com/astro-informatics/ssht/blob/c039e4e2ec70fecbc6b42ed9273e388258681c99/src/pyssht/ducc_demo.py#L85) to include -1 as one of the Spin values like so
```python
            for Spin in [0] if Reality else [-1, 0, 1]:
```
then I get this error:
```
  File "cpyssht.pyx", line 529, in pyssht.cpyssht.inverse
  File "ducc_interface.pyx", line 129, in pyssht.ducc_interface.inverse
TypeError: synthesis_2d(): incompatible function arguments. The following argument types are supported:
    1. (*, alm: numpy.ndarray, spin: int, lmax: int, geometry: str, ntheta: object = None, nphi: object = None, mmax: object = None, nthreads: int = 1, map: object = None) -> numpy.ndarray
```

I suspect that `Py_ssize_t Spin` should actually be changed to `int Spin` [here](https://github.com/astro-informatics/ssht/blob/c039e4e2ec70fecbc6b42ed9273e388258681c99/src/pyssht/ducc_interface.pyx#L106) and [here](https://github.com/astro-informatics/ssht/blob/c039e4e2ec70fecbc6b42ed9273e388258681c99/src/pyssht/ducc_interface.pyx#L210). (I believe `Py_ssize_t` is a *signed* typedef in CPython, but it looks like Cython reinterprets them as unsigned when interfacing with C code.)

### PR DESCRIPTION
**Pull request by mreineck**

### CODE REVIEW

**Comment by jasonmcewen** [comment]
Apologies @mreineck , I've just had a chance to take a look at this now.  For some reason the Python tests are failing with error: `E   ModuleNotFoundError: No module named 'pyssht.cpyssht'`.  Any idea why that might be the case?

**Comment by mreineck** [comment]
As far as I can tell, this is not related to my changes in the source code, but rather to changes i the testing enviroment (updated versions of tools perhaps?).

To verify this, I'll open a pull request that contains no real change at all; if this also produces the same `ModuleError`, the problem is not due to my changes.

**Comment by mreineck** [comment]
As you see in #68, the test failures are not caused by my changes. Sorry, I'm not sure how to fix those.

**Comment by jasonmcewen** [comment]
Ah apologies @mreineck, hadn't appreciated that.

@mdavezac @CosmoMatt Any idea why the CI fails (with no changes to the code)?  Issue appears to be with the following:

```
     from pyssht.cpyssht import *
E   ModuleNotFoundError: No module named 'pyssht.cpyssht'
```

**Pull request merged**
